### PR TITLE
Base image for fabric8-analytics-worker

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by jpopelka** [comment]
[test this]

**Comment by jpopelka** [comment]
[test this]

**Comment by jpopelka** [comment]
@msrb what else besides https://github.com/fabric8-analytics/jenkins-jobs/pull/3 do I need to run tests here ?

Or do I need to first merge Jenkinsfile into master to be able to run them ?

**Comment by msrb** [comment]
@jpopelka one needs to follow instructions detailed in https://github.com/fabric8-analytics/jenkins-jobs/blob/master/README.md to actually create new jobs in Jenkins. I will take care of that.

**Comment by msrb** [comment]
[test this]

**Comment by jpopelka** [comment]
green 🥇

**Comment by jpopelka** [comment]
[test this]

**Pull request merged**
