### PR TITLE
Lock down mercator version

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
The real purpose of this PR is to rebuild worker-base image because RHEL-based image was broken: https://github.com/rhdt/EL-Dockerfiles/pull/80

**Comment by msehnout** [comment]
So what is the purpose of locking down the version?

**Comment by msrb** [comment]
Knowing exactly what version you test with and ship. There is a RHEL-based image which ships with one version and we definitely want CentOS-based image to ship with the same version. Otherwise it's a mess.

Plus, since we build the image only once, there is no good way how to update mercator (if needed) other than some dummy readme change to force new build. This way it's clear what is going on and why the new build is needed.

**Review by msehnout — APPROVED** [review]
LGTM after the explanation

**Pull request merged**
